### ISSUE TITLE
something wrong with prolif

### ISSUE THREAD

**Issue by lkfd246** [ci-lab-cz/streamd#27]
Hi,

Dear author, thank you very much for open source this software.I have some bugs in use, I hope to get help:

*The tpr file is generated by gromacs2024.2,version=133,but I manually modified the version=129 of the tpr file
*The xtc file starts at 140ns and ends at 150ns, with a total of 501 frames

This bug occurs after using the command:

(md) [hf@DESKTOP-ODBR0IF streamd-master]$ run_prolif --xtc ./md_run/md_fit.xtc --tpr ./md_run/md_out.tpr -l MOL  -c 16 -v
2024-07-25 03:01:47 - root - INFO: Namespace(wdir_to_run=None, xtc='./md_run/md_fit.xtc', tpr='./md_run/md_out.tpr', ligand='MOL', step=1, append_protein_selection=None, wdir=None, verbose=True, hostfile=None, ncpu=16, width=15, height=10, occupancy=0.6, not_save_pics=False)
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: Gromacs version   : b'VERSION 2024.2'
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx version       : 129
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx generation    : 28
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx precision     : 4
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx file_tag      : b'release'
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx natoms        : 113710
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx ngtc          : 2
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx fep_state     : 0
2024-07-25 03:01:47 - MDAnalysis.topology.TPRparser - INFO: tpx lambda        : 0.0
Traceback (most recent call last):
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/prolif/fingerprint.py", line 506, in _run_parallel
    n_frames = traj.n_frames
AttributeError: 'FrameIteratorAll' object has no attribute 'n_frames'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hf/anaconda3/envs/md/bin/run_prolif", line 8, in <module>
    sys.exit(main())
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/streamd/prolif/run_prolif.py", line 250, in main
    start(wdir_to_run=args.wdir_to_run, wdir_output=wdir, tpr=tpr,
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/streamd/prolif/run_prolif.py", line 160, in start
    run_prolif_task(tpr, xtc, protein_selection, ligand_selection, step, verbose, output, pdb=pdb, n_jobs=ncpu, occupancy=occupancy)
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/streamd/prolif/run_prolif.py", line 70, in run_prolif_task
    fp.run(u.trajectory[::step], ligand, protein, progress=verbose, n_jobs=n_jobs)
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/prolif/fingerprint.py", line 472, in run
    return self._run_parallel(
  File "/home/hf/anaconda3/envs/md/lib/python3.10/site-packages/prolif/fingerprint.py", line 509, in _run_parallel
    frames = range(traj.start, traj.stop, traj.step)
AttributeError: 'FrameIteratorAll' object has no attribute 'start'

Thank you very much!
hf

![issue](https://github.com/user-attachments/assets/d029ef4a-2198-4896-846f-542495d74db2)

**Comment by lkfd246** [comment]
Thanks!
I just changed it manually
/ home/hf/anaconda3 \ envs \ \ lib \ python3.10 md \ site - packages \ prolif
Line 506 of the file
n_frames = 501
After that, there are no mistakes, thank you very much!
