### ISSUE TITLE
encounter error, when using Alphafold2 output protein structure for MD

### ISSUE THREAD

**Issue by nongbaoting** [ci-lab-cz/streamd#34]
encounter error, when using Alphafold2 output protein structure for MD
```
 run_md -p fold_3a_as3l_model_0.pdb --md_time 0.1 --nvt_time 100 --npt_time 100  --device gpu 
2024-12-11 15:07:50  - root - INFO: Namespace(protein='/disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/fold_3a_as3l_model_0.pdb', wdir=None, ligand=None, cofactor=None, clean_previous_md=False, hostfile=None, ncpu=96, mdrun_per_node=1, device='gpu', gpu_ids=None, ntmpi_per_gpu=1, topol=None, topol_itp=None, posre=None, protein_forcefield='amber99sb-ildn', noignh=False, md_time=0.1, npt_time=100, nvt_time=100, seed=-1, no_dr=False, not_clean_backup_files=False, steps=None, mdp_dir=None, wdir_to_continue=None, out_suffix=None, deffnm='md_out', tpr=None, cpt=None, xtc=None, ligand_list_file=None, ligand_id='UNL', activate_gaussian=None, gaussian_exe=None, gaussian_basis='B3LYP/6-31G*', gaussian_memory='120GB', metal_resnames=None, metal_cutoff=2.8, metal_charges={'MN': 2, 'ZN': 2, 'CA': 2})
2024-12-11 15:07:50  - root - INFO: Start protein preparation
2024-12-11 15:07:51  - root - INFO: Successfully finished protein preparation

2024-12-11 15:07:51  - root - INFO: Start complex preparation
2024-12-11 15:08:00  - root - INFO: Finished task N: 1. Argument: /disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0. Function: run_complex_preparation. Time: 5.226 s.
2024-12-11 15:08:00  - root - INFO: Successfully finished 1 complexes preparation

2024-12-11 15:08:03  - root - INFO: Start Equilibration steps
2024-12-11 15:15:12  - root - INFO: Finished task N: 1. Argument: /disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0. Function: run_equilibration. Time: 429.32 s.
2024-12-11 15:15:12  - root - INFO: Successfully finished 1 Equilibration step

2024-12-11 15:15:12  - root - INFO: Start Simulation step
2024-12-11 15:17:50  - root - INFO: Finished task N: 1. Argument: ('/disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0', 'md_out'). Function: run_simulation. Time: 157.566 s.
2024-12-11 15:17:50  - root - INFO: Simulation of 1 complexes were successfully finished
Finished: [('/disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0', 'md_out')]

2024-12-11 15:17:50  - root - INFO: Start Analysis of the simulations
2024-12-11 15:18:05  - root - INFO: Finished task N: 1. Argument: /disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0. Function: run_md_analysis. Time: 12.633 s.
Traceback (most recent call last):
  File "/data1/weig01/conda/envs/md/bin/run_md", line 8, in <module>
    sys.exit(main())
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/streamd/run_md.py", line 633, in main
    start(protein=args.protein,
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/streamd/run_md.py", line 412, in start
    run_rmsd_analysis(rmsd_files=rmsd_files, wdir=wdir, unique_id=unique_id,
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/streamd/analysis/run_analysis.py", line 54, in run_rmsd_analysis
    rmsd_merged_data = make_lower_case(rmsd_merged_data, cols=['system','ligand_name'])
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/streamd/analysis/run_analysis.py", line 43, in make_lower_case
    df[col] = df[col].str.lower()
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 191, in __init__
    self._inferred_dtype = self._validate(data)
  File "/data1/weig01/conda/envs/md/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 245, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!. Did you mean: 'std'?

```

**Comment by avnikonenko** [comment]
Hello!
It was a bug related to interactive rmsd analysis html generation of the protein in water systems. I have fixed it. It should work now.
Could you please uninstall the streamd package and then reinstall it again by pip install git+https://github.com/ci-lab-cz/streamd.git.
The simulation itself have finished successfully, so you can just run the 4th step for the md analysis procedure only: 
`md_run --wdir_to_continue /disk1/user/nong/proj/24-proteinDesign/24-MT2/3A_binder/alphfold3_3Aas3L/streaMD/md_files/md_run/fold_3a_as3l_model_0 --steps 4`
Hope it will work alright!
